### ISSUE TITLE
Linking.getInitialURL() returns null on Android and restarts app 

### ISSUE THREAD

**Issue by miguelespinoza** [customerio/customerio-expo-plugin#143] opened 2024-07-10 18:47 UTC
I'm working on integrating CIO with Android, and I'm not seeing any additional configurations required to get deep linking support. The [docs only require](https://customer.io/docs/sdk/expo/push-notifications/deep-links/) to set up deep link navigation using `@react-navigation/native`. I've done that, but I have two issues:

1. The app restarts, even with `config.pushClickBehaviorAndroid = PushClickBehaviorAndroid.ActivityPreventRestart;`
2. When the app restarts and triggers the `NavigationContainer` `linking` prop, the value for `Linking.getInitialURL()` is null

Is it necessary to make any updates to the `AndroidManifest.xml`, when using the `customerio-expo-plugin`?

**Comment by mrehan27** [comment] 2024-07-11 08:34
Hi @miguelespinoza. Sorry for any inconvenience caused by the behavior you mentioned. There could be multiple factors linked to this behavior, so I'm trying to narrow it down by asking a few questions to help you better.

- Can you confirm version of React Native and Expo SDKs you are using so we can ensure we are debugging the same code?
- Can you confirm if you are using Bare or Managed workflow?
- Do you have multiple push providers added to your SDK (e.g. `rnfirebase`, `expo-notifications`)? If yes, are you handling push notifications by using one of the [options mentioned in React Native docs](https://www.customer.io/docs/sdk/react-native/push-notifications/multiple-push-providers/#how-to-handle-multiple-push-providers)?
- Are you using Simple Push (only title and body), Rich Push (title, body, and image/link, or one of image or link), or Custom Payload?
- The behavior you are currently seeing is:
  - Notification displayed when app is in foreground
  - Tapping on notification restarts app despite setting `PushClickBehaviorAndroid.ActivityPreventRestart`
  - All your components are recreated in React App and `NavigationContainer` receives an empty link in `linking` prop
- Any other information or customization you made that you think might be helpful, please share with us

For your question:

> Is it necessary to make any updates to the `AndroidManifest.xml`, when using the `customerio-expo-plugin`?

Only if you are using multiple push providers and want our SDK to handle all your notifications. However, this may prevent other push providers from triggering some callbacks. If you want to continue using callbacks from other SDKs, you can implement [option 1 as suggested in our React Native SDK docs](https://www.customer.io/docs/sdk/react-native/push-notifications/multiple-push-providers/#cio-process-notification-payloads).

Please feel free to ask any more questions you have. Appreciate your cooperation while we debug this together. Have a great day!

**Comment by miguelespinoza** [comment] 2024-07-11 17:02
Hey @mrehan27, thanks for the reply!

1. SDK versions:
   * Didn't see any major changes between 3.8.0 and 3.4.0, so didn't upgrade
   * fwiw, I have iOS working with deep linking
```
"customerio-expo-plugin": "1.0.0-beta.15",
"customerio-reactnative": "3.4.0",
"expo": "50.0.8",
"react-native": "0.73.4",
```
2. Expo managed workflow
3. I do have multiple push providers, `"expo-notifications": "0.27.6"` to be exact. But I was under the impression the CIO SDK worked in tangent. I kept `expo-notifications` on iOS because it had support for provisional notification permissions. That's the only reason we use `expo-notifications`. Would there be conflicts on Android having `expo-notifications`? I recall seeing a change that allowed `expo-notifications` along with `customerio-react-native`.
4. I'm using custom_payload, this always gets me, not sure where to put the payload metadata. This is what I have right now (using rails)
```ruby
{
      transactional_message_id: message_id,
      identifiers: {
        id: recipient.id
      },
      link: message_data[:link],
      message_data:,
      custom_payload: {
        ios: {...},
        android: {
          message: {
            notification: {
              title: message_data[:title],
              body: message_data[:body],
              image: message_data[:image],
            },
            data: {
              title: message_data[:title],
              body: message_data[:body],
              link: message_data[:link],
              image: message_data[:image]
            },
          }
        }
      }
    }
```
5. The behavior you are currently seeing is: ... That's all correct. If it helps, this is what my linking prop looks like
```js
export const createNavigationLinkingConfig = ({
  ....
}): LinkingOptions<NavigationParams> => {
  return {
    prefixes: [
      Linking.createURL("/"),
      "app://",
      "https://app.is/",
    ],
    config: {
      screens: {
        ...
      },
    },
    async getInitialURL() {
      const initialUrl = await Linking.getInitialURL();
      // 🚨 This is where I expect initialUrl to exist for Android, this works on iOS
      if (initialUrl) {
        // use initialUrl to build the link
      }

      const branchParams = await getBranchParams();
      if (branchParams && Object.keys(branchParams).length > 0) {
        // use branchParams to build the link
      }
    },
    subscribe(listener) {
      const linkingSubscription = Linking.addEventListener(
        "url",
        async ({ url }) => {
          // use url to build the link
        },
      );

      const branchUnsubscribe = branch.subscribe({
        onOpenComplete: async ({ error, params, uri }) => {
          if (params?.["+clicked_branch_link"]) {
            // use params to build the link
          }
        },
      });

      return () => {
        linkingSubscription.remove();
        branchUnsubscribe();
      };
    },
  };
};
```

**Comment by mrehan27** [comment] 2024-07-11 19:45
Thanks for the great details @miguelespinoza. Much appreciated.

Thanks for sharing SDK versions. We recommend keeping SDK version up-to-date for better experience and improved performance. There isn't any fix linked to this recently so no rush on this, but updating to latest version as soon as possible is still recommended and much appreciated. I was mainly asking to make sure we rule out any potential code differences and ensure we are looking at the same version of code that your app is using.

If you are using `expo-notifications`, it could possibly be conflicting and preventing our SDK from handling notifications. Unfortunately, push notifications come with some restrictions and have different behavior across iOS and Android, due to which compatibility may differ. We are constantly working on minimizing those challenges, making the behavior consistent, and keeping our docs up-to-date for better developer experience and will continue working on improving this.

Since you mentioned you only needed `expo-notifications` for iOS mainly, can you try going with [Option 2 mentioned in React Native docs](https://www.customer.io/docs/sdk/react-native/push-notifications/multiple-push-providers/#register-messaging-service)? This will prevent any callbacks for Android from `expo-notifications` but should solve any other challenges you are facing while sending notifications from Customer.io. Since you mentioned you are on managed workflow, our expo plugin does allow implementing option 2 by just [enabling `android.setHighPriorityPushHandler` config option](https://www.customer.io/docs/sdk/expo/getting-started/#configure-the-plugin) as follows:

```
"android": {
  "setHighPriorityPushHandler": true
}
```

For the payload you shared, sorry I haven't caught up much recently with how exactly the Rails code accepts the payload, but overall this looks fine and should work for you. In case you are wondering what final payload sent from our editor is, you can always find it out by following these steps:

- Go to Push Editor on Fly
- Compose a push with desired fields using our Rich Push Editor
- Click on "Preview payload" button at top of Preview Window on the right and it should reflect final JSON we expect (You can select your desired platform iOS or Android to see their respective JSONs)

This should help you get `initialUrl` correctly. Do let me know if you still face the issue, so I can suggest next steps to narrow this down further.

Once again, appreciate your cooperation. Please feel free to post any questions you have so we can continue to help you better!

**Comment by mrehan27** [comment] 2024-07-19 14:54
Hey @miguelespinoza. From the details so far, this looks like expected behavior, so I'll go ahead and close this issue. If the above responses don't help or if you have more questions, please feel free to reach out and ask. Have a great day!

**Closed by mrehan27** 2024-07-19 14:54 UTC
