### ISSUE TITLE
`CioTracking` not found / `NotificationService-Info.plist` doesn't exist.

### ISSUE THREAD

**Issue by joeyhotz** [customerio/customerio-expo-plugin#121] opened 2024-01-18 00:55 UTC
Hey team!

Attempting to upgrade to expo 50 and seeing some issues with the customerio expo plugin and facing some issues unfortunately.

When trying to run a `pod install`, I run into this error:

```
[!] An error occurred while processing the post-install hook of the Podfile.

[!] The plist file at path `/[REDACTED]/mobile/ios/NotificationService-Info.plist` doesn't exist.
```

Additionally also seeing this error when trying to build the expo application which I assume is related:

```
❌  (ios/NotificationService/NotificationService.swift:3:8)

  1 | import Foundation
  2 | import UserNotifications
> 3 | import CioTracking
    |        ^ no such module 'CioTracking'
  4 | import CioMessagingPushAPN
  5 |
  6 | @objc


❌  (ios/NotificationService/NotificationService.swift:3:8)

  1 | import Foundation
  2 | import UserNotifications
> 3 | import CioTracking
    |        ^ no such module 'CioTracking'
  4 | import CioMessagingPushAPN
  5 |
  6 | @objc


❌  (ios/NotificationService/NotificationService.swift:3:8)

  1 | import Foundation
  2 | import UserNotifications
> 3 | import CioTracking
    |        ^ no such module 'CioTracking'
  4 | import CioMessagingPushAPN
  5 |
  6 | @objc
```

```
    "expo": "^50.0.0-preview.11",
    "customerio-expo-plugin": "^1.0.0-beta.13",
    "customerio-reactnative": "^3.3.2",
```

Would you have any insight as to how to fix the issue? We're looking to upgrade to expo 50 to be able to support a different library we'd like to use.

**Comment by joeyhotz** [comment] 2024-01-18 03:44
Done a bit more research and I've found that this might be an issue with react-native 0.73.2
https://github.com/facebook/react-native/issues/42239

There is a git patch in this [PR](https://github.com/facebook/react-native/issues/42147) for the react native node module that will solve the issue locally, however the customerio expo plugin has a deployment target of 13.0 for iOS which is incompatible with expo 50 so I will raise another issue for this.

**Comment by mrehan27** [comment] 2024-01-18 09:17
Thank you, @joeyhotz for providing the details. I really appreciate the effort you've put into identifying the root cause. Now that we know the issue and have a separate ticket for it, I'm going to close this ticket. Let's continue our discussion on the [other ticket](https://github.com/customerio/customerio-expo-plugin/issues/122) you opened.

**Closed by mrehan27** 2024-01-18 09:17 UTC
