### ISSUE TITLE
[Question] Getting Rich Push Notifications to work alongside Live Activities with Expo managed app

### ISSUE THREAD

**Issue by carozo** [customerio/customerio-expo-plugin#158] opened 2024-11-12 16:00 UTC
## New question:

Does our SDK's rich push notification NSE target work alongside Live Activities? How can they set this up? (possible docs update needed)

## Previous queston:

We are using `expo-notifications` to send some notifications and the customerio sdk to send others. The issue we're having is that Expo is handling all the notifications (even customerio ones) and that prevents rich push notifications from working. I have followed [this guide](https://docs.customer.io/sdk/react-native/push-notifications/multiple-push-providers/) and I was able to get the rich push notification to show up when the app is in foreground, but I can't seem to make it work in the background.

I see that in the docs there's a section dedicated to setup the background listeners using firebase's `setBackgroundMessageHandler`, and I tried a similar approach using `expo-notifications`:

```
TaskManager.defineTask(BACKGROUND_NOTIFICATION_TASK, async ({ data }) => {
  await CustomerIO.pushMessaging()
    .onBackgroundMessageReceived(data)
    .then(handled => {
      if (!handled) {
        console.log('Notification not handled by Customer.io')
      }
    })
})
```

but that always logs 'Notification not handled by [Customer.io](http://Customer.io)', even if it was a customerio push notification. This is happening to me in iOS as well. Any help would be greatly appreciated. Thanks!

**Comment by carozo** [comment] 2024-11-12 16:14
Closing this because I found the issue. I was passing the wrong object to `onBackgroundMessageReceived`, should have passed data.notification

**Comment by jordanhailey** [comment] 2024-11-19 00:58
Troubleshooting has continued within a support conversation. Closing this issue as it appears the problem is related to Live Activities.

**Closed** 2024-11-19 02:42 UTC
