### ISSUE TITLE
Push deep links not working when using multiple push notification modules (ie `expo-notifications`)

### ISSUE THREAD

**Issue by wanschi** [customerio/customerio-expo-plugin#83] opened 2023-06-15 13:31 UTC
Hello,

I have integrated the Customer.io Expo SDK. It seems like everything is working. 

- I can start the permission request
- A token is issued
- I have turned on rich push
- I receive push messages (also with photos, so rich messages are enabled and configured).

What does not work though are deep links. Deep links "dry" launch the app too (tested with uri-scheme), but not with a Customer.io push notification. Also, Linking.useURL() is not triggered after I receive a push notification and launch the app. I always end up in the homescreen of the app. 

I have also tried debugging the whole thing via Swift. But it seems like it doesn't jump into the code for the deep links at all.

"expo": "~48.0.18",
"customerio-expo-plugin":"^1.0.0-beta.10",
"customerio-reactnative": "2.4.0",

(Unfortunately, the latest version of customerio-reactnative does not work for us).

Thank you

**Comment by ami-aman** [comment] 2023-06-15 14:21
Hi @wanschi 

Thanks for reaching out and apologies for the inconvenience caused. 

I would like to let you know that this is a known issue with our expo plugin. We are actively working on improving our plugin, but I'm unable to provide a specific timeline for the resolution at this moment. Rest assured I will make sure to raise this with our team internally and get the fix out of the door soon. Your patience and understanding are greatly appreciated.

Meanwhile, let us know if you have any other issues.

**Comment by heuels** [comment] 2023-06-23 18:17
Following! We at @on-deck would also love to use deep links from the CIO push notifications.

**Comment by dgsunesen** [comment] 2023-06-26 18:05
Same here. Deep link support would be awesome.

@wanschi if I may ask you a question? Do you receive Customer.io push notifications when your app is foregrounded? Currently I only receive them when the app is backgrounded.

**Comment by wanschi** [comment] 2023-06-26 18:26
@dgsunesen Yes, same here. We're only receive them in the background. After opening them you'll end up on the first screen. In our case this is the left item in the root tab bar. 

@ami-aman Can you give us a rough estimation. Since our plan is to release in 3 weeks we'll need to know if we need to switch to another push notification solution.

**Comment by dgsunesen** [comment] 2023-06-27 06:03
@ami-aman Just FYI, I'm in contact with your Technical Support Engineers who promised me to reach out to you guys (Mobile team) on an ETA on when this could be fixed :) 

We're also planning on releasing a new version of app including Customer.io, but not being able to receive push notifications while app is foregrounded as well as deep links not working properly could be quite the party killer for us :(

**Comment by ami-aman** [comment] 2023-06-27 08:09
@wanschi @dgsunesen 
Thank you for reaching out and sharing your concerns. I completely understand the frustration caused by the current issues with push notifications and deep links in you app. Please rest assured that our Mobile team is actively working on resolving these issues to provide a seamless experience for our users.

I appreciate your proactive approach in contacting our Technical Support Engineers, who are in direct communication with our Mobile team. While we don't have a specific ETA at the moment, I want to assure you that addressing these issues is our top priority. We are aiming to have the fixes implemented by the end of next week.

However, I want to be transparent and avoid providing a hard timeline at this point. Our team is working diligently to resolve these issues as quickly as possible, but we want to ensure that the solutions are thoroughly tested and reliable before releasing them to our users.

 I apologize for any inconvenience caused, and I genuinely appreciate your patience and understanding.

**Comment by dgsunesen** [comment] 2023-07-10 18:19
@ami-aman What's the status on this one? :)

**Comment by ami-aman** [comment] 2023-07-11 19:23
Hi @dgsunesen 

Our team is working on this issue and we expect the fix to be released either end of this week or early next week. We are trying our best to get this fix out of the door as soon as possible.

I will make sure to update this conversation once the fix has been released. Let me know if you have any other question or suggestion for us. 

Apologies for the inconvenience.

**Comment by wanschi** [comment] 2023-07-31 14:53
@ami-aman Hello, are there any updates on the timeline? 

Thanks for your work guys!

**Comment by ami-aman** [comment] 2023-08-07 11:59
@wanschi 
I'm excited to that the fix for deeplinks has been successfully deployed in release version [1.0.0-beta.13](https://github.com/customerio/customerio-expo-plugin/releases/tag/1.0.0-beta.13). This fix introduces a new configurable property named `handleDeeplinkInKilledState` and can be used as :

```
"ios": {
            "handleDeeplinkInKilledState": true,
            "pushNotification": {
             .
             .
             .
            }
       }
```
You can read more about the fix in our docs [here](https://customer.io/docs/sdk/expo/getting-started/#configure-the-plugin). 

Thank you for your understanding throughout this process. I am closing this ticket for now. Should you have any inquiries, please feel free to re-open the ticket and reach out to us at any time.

**Comment by dgsunesen** [comment] 2023-08-07 12:20
@ami-aman Great stuff! Does this also include receiving notifications when the app is foregrounded? I know @wanschi and his team experienced the same issue where you'd only receive notifications when app is backgrounded.

Great job!

**Comment by ami-aman** [comment] 2023-08-07 15:06
@dgsunesen Thank you ! Yes, this release also addresses the issue where you can now receive notifications when the app is in foreground.

Add a property `ios. handleNotificationClick` to `app.json` or `app.config.js` to make use of the feature. More about the configurable properties can be found [here](https://customer.io/docs/sdk/expo/getting-started/#configure-the-plugin) in our docs.

Let us know if you face any issues.

**Comment by dgsunesen** [comment] 2023-08-07 15:08
@ami-aman This is nice! I will definitely get back if I see any issues. 

Do you by any chance have any discord or slack channel where to reach you guys ?

**Comment by ami-aman** [comment] 2023-08-08 18:46
@dgsunesen Thanks for testing out the fix. I really appreciate it.

Unfortunately, `expo-notifications` does not work well when setting the delegate for `UNUserNotificationCenter`. Our package needs to have this delegate set for certain features, such as to show push notifications in foreground etc.

We have introduced a few JavaScript methods for [tracking push metrics](https://customer.io/docs/sdk/expo/push/#metrics-javascript) that help `expo-notifications` and our package run in parallel. We are also working on bringing more features to let both libraries run together without any interference. However, we do not have any workaround to let both event listeners work in parallel at this time.

Your observation regarding notifications in the foreground is accurate: enabling `handleNotificationClick` to true will indeed result in notifications being received while the app is in foreground but this might conflict with `expo-notifications`. We are constantly working on making our plugin better and introducing features that will help address this inconvenience.

**Comment by dgsunesen** [comment] 2023-08-09 06:36
@ami-aman I see. It would really be a killer feature to be able to do this, as we are so deeply dependant on the notifications we are already sending out using `expo-notifications`. Also, using Customer.io and be able to send engagement content via push notifications and be able to actually deep link to certain places in the app is quite crucial for our business, so I indeed think this is something that needs to be addressed.

I know it works when using Intercom in parallel with `expo-notifications` — I've tested it a bit there. Though it only seems that the push notification arrives when the app is backgrounded, however, deep links are indeed working. Perhaps you could get some inspirations from there?

https://github.com/intercom/intercom-react-native

**Comment by berkcoker** [comment] 2023-08-14 07:02
Deeplinks do not work for us with these configurations. It actually only works when the app is in killed state.  Seems like there's an issue with `handleNotificationClick`

**Comment by ami-aman** [comment] 2023-08-14 13:20
@dgsunesen I appreciate your interest in our plugin and for sharing the reference plugin. We understand that you have specific requirements, and we are constantly working to improve the plugin to meet those requirements. I will pass your feedback on to the team.

Again, thank you for your feedback. It helps us to improve our products and services. Your feedback is immensely helpful to us.

**Comment by berkcoker** [comment] 2023-08-14 16:42
Yes followed the instructions and can confirm that the deep links are working (both when the app is killed and when I try to open the link from the Notes app). The issue seems to be that background responses (notification taps) don't trigger the desired event for the listener. Sidenote: we use `expo-notifications` for local notifications but don't rely on their listeners. When I tried to disable CustomerIO's `handleNotificationClick` and tried to rely on Expo Notifications that didn't work either

**Comment by dgsunesen** [comment] 2023-08-14 18:00
@ami-aman as Expo seems to be more and more adopted I would highly recommend that it could be working seamlessly together with that as well, as I could see many would rely on `expo-notifications` for local notifications in combination with something like customer.io :)

**Comment by levibostian** [comment] 2023-08-17 18:46
Hello, I am a teammate of Aman's. I'll try to help in this issue as well. 

The `handleNotificationClick` feature in our Expo plugin is only useful when Customer.io is the only push notification module that you are using in your app. `handleNotificationClick` will tell our Expo plugin that the Customer.io SDK should be the module that handles all push notification interactions and no other module. 

It seems as though both of you are using `expo-notifications`. This is a module that also can interact with notifications in your app. Unfortunately, only 1 module is able to be the handler of push notification interactions. This is a limitation set by iOS. From working with customers, we have seen that it is best to make `expo-notifications` the handler and therefore, make sure to set `handleNotificationClick` to `false`. 

When another module, such as `expo-notifications`, is responsible for handling push notification being delivered and clicked, your setup with the Customer.io SDK requires a couple more steps since it is no longer handling the clicks. U

Use `expo-notification` listeners to listen for push events in your app. Specifically, when a push is received on the device and when a push is clicked on the device. 

* When your app receives a push notification, [send the push to the Customer.io SDK](https://customer.io/docs/sdk/react-native/push-notifications/multiple-push-providers/#cio-process-notification-payloads). 
* When a push notification is clicked, [send the push notification to the Customer.io SDK for metrics tracking](https://customer.io/docs/sdk/expo/push-notifications/push-metrics/#metrics-javascript). 

I hope that this helps give clarity to the use of `handleNotificationClick`.

**Comment by levibostian** [comment] 2023-08-17 18:55
In regards to the use of `handleDeeplinkInKilledState`, this feature is designed to add more stability to deep link handling when your app is in the killed state. This feature should not interfere with the unrelated `handleNotificationClick` feature. 

Are you using [Expo's linking module](https://docs.expo.dev/guides/linking/) for deep link handling in your app?

**Comment by levibostian** [comment] 2023-08-29 17:03
Great, thank you for sharing that. 

We have internally logged this issue with deep links not getting opened on a Customer.io push when multiple SDKs are installed. Unfortunately, I cannot share estimates for when we are able to ship a fix for this. 

I'll re-open this issue to help track when this issue becomes resolved. Thank you again for all who have been involved in helping us better understand this issue.

**Comment by dgsunesen** [comment] 2023-10-05 03:54
@levibostian Any progress on this issue?

**Comment by levibostian** [comment] 2023-10-05 19:39
Thanks for the patience and cooperation, @dgsunesen. 

This issue is more complex then we originally anticipated. I don't have dates to share with you today, except for the fact we are working on this.

**Comment by levibostian** [comment] 2023-10-18 16:10
I am happy to share that I have a prototype for this feature and would greatly appreciate feedback on it. 

There are so many environments to test against with an Expo app. We greatly appreciate everyone able to help us with testing! 

We are looking for multiple people to install this prototype code into their app, test that the Customer.io SDK *and* `expo-notifications` both work as intended. We expect that that both libraries are more compatible together by this new feature. 

> Note: The feature is in an unstable prototype condition at the moment. We do not suggest running this code in production. It's purpose is for testers to test it to see if they get the desired outcome. After testing concludes, we will move forward with the next steps making this feature stable. 

# How to install 

Install Expo plugin from git branch: 
* `npm install --save https://github.com/customerio/customerio-expo-plugin/tarball/levi/reliable-open-metrics`

The prototype only works with 1 specific version of the React Native SDK. Make sure your `package.json` file contains this line exactly as below:
```json
"customerio-reactnative": "3.1.12",
```

* For your `app.json` file, use a basic configuration set for the Expo plugin. No need to include `handleNotificationClick` as discussed in this issue. 

Here is an example plugin configuration that has been tested internally: 
```json
    "plugins": [
      [
        "customerio-expo-plugin",
        {
          "android": {
            "googleServicesFile": "./files/google.json",
            "setHighPriorityPushHandler": true
          },
          "ios": {
            "pushNotification": {
              "useRichPush": true,
              "env": {
                "siteId": "put your site id here",
                "apiKey": "put your api key here",
                "region": "us"
              }
            }
          }
        }
      ],
```

* Run `expo prebuild --clean` to re-create native files. 

# How to test 

* Make sure that both `expo-notifications` and Customer.io is installed in your app. We need to test the compatibility between the two libraries. 
* Send yourself a push notification from Customer.io with a deep link. Touch the push notification. You should see your app launch and navigate to your deep link destination screen. Assuming that your [app is configured correctly to handle deep links](https://customer.io/docs/sdk/expo/push-notifications/deep-links/#set-up-deep-links) from Customer.io, you should see deep links go to their destination. 
* Run tests in your app that validate the `expo-notifications` features are also working as expected. You should expect to see Expo notifications work like it did before installing the Customer.io SDK. 

* If you could, please send us your test results to `win@customer.io` instead of in this issue to prevent noise. In your email, reference this GitHub issue and my GitHub username. The team will direct messages accordingly. 

In your email, please include....
- Expected outcome from your testing. 
- Actual outcome from your testing. If the actual outcome was not what you expected, please describe in detail what steps that you did to reproduce the issue or your app's environment. 
- Copy of `app.json` Expo config file, `package.json` file, `ios/Podfile` file, and `ios/HostAppName/AppDelegate.mm` file generated after `expo prebuild --clean`. 
- URL from your Customer.io workspace Activity Log with the push notification delivery that you sent yourself for testing. 

Thank you! Have an awesome day.

**Comment by dgsunesen** [comment] 2023-10-19 03:30
@levibostian Wow! This sounds promising! I'll make sure to get this tested with our setup :)

**Comment by levibostian** [comment] 2023-11-13 14:41
Thank you for the feedback, León. Our team is currently working on making improvements to this feature. We hope that when shipped, the issues that everyone is encountering in this issue become resolved. 

> is there any way people can contribute to those?

Yes! You can give suggestions while you browse a webpage. See this screenshot for how to find this form: 

![CleanShot 2023-11-13 at 08 38 26@2x](https://github.com/customerio/customerio-expo-plugin/assets/2041082/c4d43918-333c-4de9-8fa8-e4cbe18d90eb)

**Closed** 2024-02-12 17:39 UTC

**Comment by levibostian** [comment] 2024-02-12 18:28
Happy to announce the latest Customer.io Expo plugin release `1.0.0-beta.14` includes increased compatibility with `expo-notifications` for reporting `opened` push metrics as well as deep links being launched when a push is clicked. 

We hope you enjoy this new feature!
